services:
  app:
    build: .
    command: ["./wait-for-it.sh", "gcs:9023", "--timeout=30", "--", "poetry", "run", "python", "-m", "main"]
  gcs:
    image: oittaa/gcp-storage-emulator:v2024.08.03
    command: ["start","--host", "gcs", "--p", "9023", "--default-bucket", "test-bucket"]
